[package]
name = "usugumo"
version = "3.0.0"
edition = "2024"
build = "build.rs"

[lib]
name = "usugumo_rs"
crate-type = ["cdylib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = 3
lto = true
strip = true
codegen-units = 1
incremental = false
debug = false

[dependencies]
obfstr = "0.4.6"
